before_script:
  - "bundle exec rake refinery:testing:dummy_app > /dev/null"
script: "bundle exec rspec ./spec"
notifications:
  email:
    - alexander@wenzowski.com
env:
  - DB=postgresql
  - DB=mysql
language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
  - jruby-18mode
  # - jruby-19mode
  # - rbx-18mode
  # - rbx-19mode
# matrix:
#   allow_failures:
#     - rvm: rbx-18mode     # ignore until rubinius #1670 fix is merged
#     - rvm: rbx-19mode     # ignore until rubinius #1670 fix is merged
#     - rvm: jruby-19mode   # ignore until refinerycms #1670 is fixed
